version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=ng-project
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
  api:
    image: node:latest
    build:
      context: "./server"
    environment:
      - EXTERNAL_PORT=5000
      - DATABASE=ng-project,
      - USERNAME=postgres,
      - HOST=localhost,
      - PASSWORD=postgres_password,
      - POSTGRES_PORT=5432
    volumes:
      - ./server:/app
    depends_on:
      - postgres
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
volumes:
  nps_data: {}
