version: "3"
services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=ng-project
    ports:
      - "3002:5432"
  api:
    container_name: api
    image: node:latest
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - EXTERNAL_PORT=5000
      - DATABASE=ng-project,
      - USERNAME=postgres,
      - HOST=postgres,
      - PASSWORD=postgres_password,
      - POSTGRES_PORT=5432
    volumes:
      - ./server/data:/var/lib/postgresql/
      - ./server:/app
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    links:
      - postgres
  client:
    container_name: client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    links:
      - api
    ports:
      - "3000:3000"